### ISSUE TITLE
Create automated builds on hub.docker.io from this repo

### ISSUE THREAD

**Issue by monotek** [zammad/zammad-docker#11]
* Delete old zammad/zammad
* Create new one via: https://hub.docker.com/add/automated-build/zammad/github/orgs/
* Rename from zammad-docker to zammad
* Pushes to this repo will trigger builds on https://hub.docker.io
* Manually trigger first build from https://hub.docker.com/r/zammad/zammad/~/settings/automated-builds/

**Comment by thorsteneckel** [comment]
Hi @monotek - our plan was to build a new version of the zammad docker image when:

- something gets pushed
- a new stable version of zammad is ready

Can we cover the second case with this?

**Comment by monotek** [comment]
As Docker and Vagrant are more or less only meaned for developers / testers (at least they are in the development section of the documentation now) i used the develop version of the packager.io packages inside the Dockerfile/Vagrantfile at the moment. 

If we also want a stable version for testers we could use a second branch, where stable packages are used and where packages are build manually in DockerHub. 

But maybe we don't need to push new Docker/Vagrant versions with new Zammad Versions, because we could add an apt or yum update at the beginning of the run process. So evry start would give you the most recent version of Zammad stable/unstable.

What do you think?

**Comment by monotek** [comment]
done... closing...
