### ISSUE TITLE
current docker develop build fails to display home screen

### ISSUE THREAD

**Issue by qschneider** [zammad/zammad-docker#12]
"docker run -ti -p 80:80 --name zammad-dev zammad/zammad:develop" just displays the nginx default page on http:/localhost.

Reason is that in the develop-build the zammad.conf in /etc/nginx/sites-enabled is missing.
In contrast, by pulling zammad/zammad:stable it is included and everything is fine.

Cheers

**Comment by monotek** [comment]
@martini
this is because of your "set -e" change in postinstall.sh.
the script fails because the systemctl command doe's not work in docker.
i'll try to fix it via docker_detect function...

**Comment by monotek** [comment]
fixed in https://github.com/zammad/zammad/commit/1be5a72dfeafdabe17728be338eeb1a48e6cc121

new docker image will be build after packager.io packages are updated...

**Comment by monotek** [comment]
Fixed in current develop package...

```
docker pull zammad/zammad:develop
docker run -ti -p 80:80 zammad/zammad:develop
```
