### ISSUE TITLE
Elasticsearch 5.1.1 install is failing

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad-docker#13]
Adding `set -e` (I prefer `set -ex`) to `scripts/docker.sh` shows that this script fails when installing Elasticsearch 5.1.1. This used to work with 5.0.1.

Here's what happens:
```
Setting up elasticsearch (5.1.1) ...
Couldn't write '65536' to 'vm/mmap_min_addr', ignoring: Read-only file system
Couldn't write '4 4 1 7' to 'kernel/printk', ignoring: Read-only file system
Couldn't write '1' to 'net/ipv4/tcp_syncookies', ignoring: No such file or directory
Couldn't write '2' to 'net/ipv6/conf/default/use_tempaddr', ignoring: Read-only file system
Couldn't write '1' to 'kernel/kptr_restrict', ignoring: Read-only file system
Couldn't write '1' to 'kernel/yama/ptrace_scope', ignoring: No such file or directory
Couldn't write '176' to 'kernel/sysrq', ignoring: Read-only file system
Couldn't write '1' to 'fs/protected_symlinks', ignoring: Read-only file system
Couldn't write '1' to 'fs/protected_hardlinks', ignoring: Read-only file system
Couldn't write '1' to 'net/ipv4/conf/all/rp_filter', ignoring: Read-only file system
Couldn't write '2' to 'net/ipv6/conf/all/use_tempaddr', ignoring: Read-only file system
Couldn't write '262144' to 'vm/max_map_count', ignoring: Read-only file system
Couldn't write '1' to 'net/ipv4/conf/default/rp_filter', ignoring: Read-only file system
dpkg: error processing package elasticsearch (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (229-4ubuntu12) ...
Errors were encountered while processing:
 elasticsearch
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c PACKAGER_REPO="$PACKAGER_REPO" /bin/bash -l -c /tmp/docker.sh' returned a non-zero code: 100
```

I haven't found a solution for this yet. Elasticsearch seems to install fine on jessie (the official [elasticsearch](https://hub.docker.com/_/elasticsearch/) repo is based on `openjdk`, which is based on `jessie`), but not on `ubuntu:16.04`.

In any case, `set -e` should be added to `scripts/docker.sh` to fail the build when the script fails.

**Comment by monotek** [comment]
For now you can use my docker compose repo: https://github.com/monotek/zammad-docker-compose

Imho there is just a sysctl command missing before es install/run:
sysctl -w vm.max_map_count=262144

Can't try it myself before next year.

**Comment by olivergrahl** [comment]
There's going to be support for a [SKIP_SET_KERNEL_PARAMETERS](https://github.com/elastic/elasticsearch/pull/21899/commits/c2b5e7ee000afcdaa9d7eb59028657023c4339cf) environment variable in the next Elasticsearch release. 

Until then, I helped myself with this evil approach:
```
mv /lib/systemd/systemd-sysctl /lib/systemd/systemd-sysctl_
apt-get --no-install-recommends -y install elasticsearch
mv /lib/systemd/systemd-sysctl_ /lib/systemd/systemd-sysctl
```

I'd still suggest to use `set -e` to make the build fail on any issues.

**Comment by monotek** [comment]
For now "set -e" just would fail using the docker image. 
Even if dpkg throws an error the image works and Elasticsearch is started.
I'll like to wait for the 5.1.2 fix until anything is changed.

**Comment by monotek** [comment]
Fixed in https://github.com/zammad/zammad-docker/commit/a7464f13314b6071aa8e1a1ce2f905313117986e

**Comment by jmreymond** [comment]
same issue with ES 5.2.2 when installing on lxc container

sudo dpkg -i /tmp/elasticsearch-5.2.2.deb 
Sélection du paquet elasticsearch précédemment désélectionné.
(Lecture de la base de données... 45920 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de /tmp/elasticsearch-5.2.2.deb ...
Dépaquetage de elasticsearch (5.2.2) ...
Paramétrage de elasticsearch (5.2.2) ...
Installation de la nouvelle version du fichier de configuration /etc/elasticsearch/elasticsearch.yml ...
Installation de la nouvelle version du fichier de configuration /usr/lib/systemd/system/elasticsearch.service ...
Installation de la nouvelle version du fichier de configuration /etc/init.d/elasticsearch ...
Installation de la nouvelle version du fichier de configuration /etc/default/elasticsearch ...
Couldn't write '1' to 'kernel/yama/ptrace_scope', ignoring: Read-only file system
Couldn't write '176' to 'kernel/sysrq', ignoring: Read-only file system
Couldn't write '65536' to 'vm/mmap_min_addr', ignoring: Read-only file system
Couldn't write '4 4 1 7' to 'kernel/printk', ignoring: Read-only file system
Couldn't write '1' to 'kernel/kptr_restrict', ignoring: Read-only file system
Couldn't write '1' to 'fs/protected_hardlinks', ignoring: Read-only file system
Couldn't write '1' to 'fs/protected_symlinks', ignoring: Read-only file system
Couldn't write '262144' to 'vm/max_map_count', ignoring: Read-only file system
dpkg: erreur de traitement du paquet elasticsearch (--install) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Traitement des actions différées (« triggers ») pour systemd (231-9ubuntu3) ...
Des erreurs ont été rencontrées pendant l'exécution :
 elasticsearch
