### ISSUE TITLE
"waiting for zammad to be ready..."

### ISSUE THREAD

**Issue by OlliM** [zammad/zammad-docker#14]
After starting the image, it stays in an endless loop saying:
"waiting for zammad to be ready..."

Even after waiting 30 minutes, the logs were filled with that message.

Is that a known issue or is any reason known for that?

**Comment by monotek** [comment]
Cant reproduce. Started Zammad via: 

* docker pull zammad/zammad
* sysctl -w vm.max_map_count=262144
* docker run -ti -p 80:80 zammad/zammad

> [ ok ] Starting PostgreSQL 9.4 database server: main.
> [....] Starting Elasticsearch Server:sysctl: setting key "vm.max_map_count": Read-only file system
> . ok 
> [ ok ] Starting Postfix Mail Transport Agent: postfix.
> starting zammad....
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> 
> Zammad is ready! Visit http://localhost in your browser!
> If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!
> 

Whats in the logs of the container?
You can open a shell in the running container via:
docker exec -ti $(docker ps -a | grep "zammad/zammad" | awk '{print $1}') /bin/bash

**Comment by OlliM** [comment]
Hi monotek

Thanks for your feedback. I got this from the shell of the running container:

Puma starting in single mode...
* Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 30
* Environment: production
scheduler: process with pid 326 started.
! Unable to load application: PG::ConnectionBad: FATAL:  the database system is starting up
FATAL:  the database system is starting up
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
PG::ConnectionBad: FATAL:  the database system is starting up
FATAL:  the database system is starting up

  /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'

**Comment by monotek** [comment]
I guess the database is not yet ready... 

I just added another until loop to wait for postgres first: https://github.com/zammad/zammad-docker/commit/b9894694065d6bfde1a780335f96d6f8bde5e450

Please pull new image with: 

* docker pull zammad/zammad

When builds @ https://hub.docker.com/r/zammad/zammad/builds/ are ready...

**Comment by monotek** [comment]
Does it work for you now?

**Comment by OlliM** [comment]
Works perfectly now, thanks a lot for fixing!
