### ISSUE TITLE
Cannot access cert-snakeoil.key on startup

### ISSUE THREAD

**Issue by Chessmasterrr** [zammad/zammad-docker#16]
Following the official documentation (https://docs.zammad.org/en/latest/contributing-install-docker.html) I wanted to test zammad. Therefore I tried to start the docker container with
`docker container run -ti --name zammad -p 80:80 zammad/zammad`  
which leads to the following error:
`Starting PostgreSQL 9.4 database server: main[....] Removed stale pid file. The PostgreSQL server failed to start. Please check the log output: 2017-03-30 09:28:43 UTC [27-1] FATAL: could not access private key file "/etc/ssl/private[FAILcert-snakeoil.key": Permission denied ... failed!
 failed!`

I have a working docker environment and followed the documentation, so I assume this is a bug in the container?

**Comment by monotek** [comment]
Cant reproduce:

> docker container run -ti --name zammad -p 80:80 zammad/zammad
> [ ok ] Starting PostgreSQL 9.4 database server: main.
> [....] Starting Elasticsearch Server:sysctl: setting key "vm.max_map_count": Read-only file system
> . ok 
> [ ok ] Starting Postfix Mail Transport Agent: postfix.
> starting zammad....
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> waiting for zammad to be ready...
> 
> Zammad is ready! Visit http://localhost in your browser!
> If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!
> 
> root@6545561da345:/opt/zammad#

**Comment by Chessmasterrr** [comment]
After some further investigation it looks like a AUFS bug in my docker environment (see here: https://github.com/docker/docker/issues/783). So it is a problem with the underlying filesystem which denies the permission for the .key file.
 
Locally I'm running Ubuntu 14.04 (kernel 3.13) which has the problem and the container fails to start.
When I test it in a vm with Ubuntu 16.04 it is working, also in a vm with Ubuntu 14.04.2 (kernel 3.16).

So I will simply test zammad in a vm and be happy. But maybe you want to use a workaround from the issue linked above in your container to prevent the issue for other users with old kernel. If not feel free to simply close this issue since most of the people will use newer kernel versions ;-).

**Comment by monotek** [comment]
I think we won't workaround the aufs bug as its not directly related to Zammad and the problem is now documented in this issue.

Thanks for the feedback :-)
