### ISSUE TITLE
Waiting and blank Page...

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad-docker#17]
I'm running Zammad in container and after using "xsc sync" to synchronise my repository I am facing and stucking in "Waiting blank" page.

This is status docker-compose up after running it:

zammad-websocket_1 | websocket server waiting for zammads railsserver to be ready...
zammad-scheduler_1 | scheduler waiting for zammads railsserver to be ready...
zammad-railsserver_1 | * Listening on tcp://0.0.0.0:3000
zammad-railsserver_1 | Use Ctrl-C to stop
zammad-railsserver_1 | 2017-04-03 14:28:51 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
zammad-railsserver_1 | 2017-04-03 14:28:51 +0000: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
zammad-railsserver_1 | ---
zammad-railsserver_1 | 2017-04-03 14:28:53 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
zammad-railsserver_1 | 2017-04-03 14:28:53 +0000: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.0 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2"}
zammad-railsserver_1 | ---
zammad-websocket_1 | 2017-04-03T14:29:05Z:client(-) check unused idle connections...

-------------------------------------------------------------------------------------------------------------------------------
Details:
docker-compose(master)> docker --version
Docker version 17.03.1-ce, build c6d412e

docker-compose(master)>docker-compose --version
docker-compose version 1.11.2, build dfed245

Centos 7 as the host.

**Comment by monotek** [comment]
Please watch where you open your requests. Your issue belongs to https://github.com/zammad/zammad-docker-compose

Do you try it locally or on remote server?
On remote server you'll have to edit the nginx.conf servername which is configured for "localhost" at the moment.

**Comment by hamzehmohammadnia** [comment]
Thank you for your reply. sorry for that, I thought since Im runnig Zammad on container maybe should I open it here...


Im running it locally on container. Should I edit that too on local?

**Comment by monotek** [comment]
depends on what hostname you want to use.
If you want to use http://localhost you have nothing to do.

**Comment by monotek** [comment]
As this is the wron repo and you have another issue open @ https://github.com/zammad/zammad-docker-compose/issues/13 i'm closing this one.
