### ISSUE TITLE
Official backup script does not work in the container

### ISSUE THREAD

**Issue by tumbl3w33d** [zammad/zammad-docker#19]
### Infos:

* Docker version: Docker version 17.05.0-ce, build 89658be
* Operating system (Docker host): Linux zammad 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

### Expected behavior:

* Backup is created in `/var/tmp/zammad_backup/`

### Actual behavior:

* Backup script fails to execute because of hardcoded paths that don't exist
``` bash
zammad@820f33d582db:~$ /home/zammad/contrib/backup/zammad_backup.sh
/home/zammad/contrib/backup/zammad_backup.sh: line 9: /opt/zammad/contrib/backup/config: No such file or directory
/home/zammad/contrib/backup/zammad_backup.sh: line 12: /opt/zammad/contrib/backup/functions: No such file or directory
/home/zammad/contrib/backup/zammad_backup.sh: line 15: check_database_config_exists: command not found
/home/zammad/contrib/backup/zammad_backup.sh: line 17: delete_old_backups: command not found
/home/zammad/contrib/backup/zammad_backup.sh: line 19: get_backup_date: command not found
/home/zammad/contrib/backup/zammad_backup.sh: line 21: backup_dir_create: command not found
/home/zammad/contrib/backup/zammad_backup.sh: line 23: backup_files: command not found
/home/zammad/contrib/backup/zammad_backup.sh: line 25: backup_db: command not found
```
caused by the following lines in `zammad_backup.sh`
``` bash
# import config
. /opt/zammad/contrib/backup/config

# import functions
. /opt/zammad/contrib/backup/functions
```
Now you can be smart and work around this issue by creating a symlink using
``` bash
ln -s /home/zammad /opt/zammad
```
but while you're still busy enjoying your own cleverness you will try running the backup script again and will get to the next bunch of errors.
``` bash
zammad@820f33d582db:/$ /home/zammad/contrib/backup/zammad_backup.sh
find: `/var/tmp/zammad_backup/*_zammad_*.gz': No such file or directory
tar: Removing leading `/' from member names
su: must be run from a terminal
mv: cannot stat '/tmp/20170620133837_zammad_db.psql.gz': No such file or directory
```
So to make it short - **the backup script does not work in the containerized version**.

### Steps to reproduce the behavior:

* launch the zammad docker setup, using the images from the [compose repo](https://github.com/zammad/zammad-docker-compose)
* enter the container `zammad-railsserver` using `docker exec -it zammad-railsserver bash`
* execute `/home/zammad/contrib/backup/zammad_backup.sh`

P.S.: If you prefer, I can move the issue over to the compose repo.

**Comment by monotek** [comment]
zammad-railsserver is not part of the docker container but of the docker-compose containers (https://github.com/zammad/zammad-docker-compose). 

The docker container is started by:
* sysctl -w vm.max_map_count=262144
* docker container run -ti --rm --name zammad -p 80:80 zammad/zammad

And the backups seems to work without problems there:

```
root@5c6cafed3c93:/opt/zammad# cd /opt/zammad/contrib/backup/
root@5c6cafed3c93:/opt/zammad/contrib/backup# rm config      
root@5c6cafed3c93:/opt/zammad/contrib/backup# cp config.dist config
root@5c6cafed3c93:/opt/zammad/contrib/backup# bash zammad_backup.sh 

# Zammad backup started - Tue Jun 20 15:08:11 UTC 2017!

creating file backup...
tar: Removing leading `/' from member names
creating postgresql backup...

# Zammad backuped successfully - Tue Jun 20 15:08:14 UTC 2017!
```

So i close this issue here. 
Please recreate in docker-compose repo.
