### ISSUE TITLE
Docker Hub needs to point to the "master" branch

### ISSUE THREAD

**Issue by sahuk** [zammad/zammad-docker#21]
### Infos:

* Docker version: 17.06.0-ce, build 02c1d87  
* Operating system (Docker host): boot2docker

### Expected behavior:

* Docker hub should be able to build the docker image

### Actual behavior:

* Build fails due to lack of a "develop" branch. Reconfigure docker-hub to use the "master" branch.

### Steps to reproduce the behavior:

See https://hub.docker.com/r/zammad/zammad/builds/bhpwfndkyjkwaa9zmqstlku/

**Comment by monotek** [comment]
Was a mistake. Already fixed.
