### ISSUE TITLE
Welcome to Nginx when trying to access Zammand backend

### ISSUE THREAD

**Issue by froemken** [zammad/zammad-docker#22]
### Infos:

* Docker version: Docker version 17.03.1-ce, build c6d412e
* Operating system (Docker host): Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-21-generic x86_64)

### Expected behavior:

* See Zammad backend in Browser by my own domainname or IP-Address

### Actual behavior:

* I see "Welcome to nginx on Debian" when I try to open Zammand backend from remote

### Steps to reproduce the behavior:

* sysctl -w vm.max_map_count=262144
* docker container run -ti --rm --name zammad -p 125:80 zammad/zammad
* edit: /etc/nginx/sites-enabled/zammad.conf
* change: server_name to mydomain.de
* service nginx restart

I have installed zammad on a remote server. Only shell available. CMD:links can't open http://localhost. I have created a port forwarding from my local machine to my remote server:

ssh -L 8080:127.0.0.1:125 mydomain.de

Now I can access Zammad backend with localhost:8080 on my local machine. But that's still not what I want. I want to access Zammad backend with http://mydomain:125

Nice greetings from germany

Stefan

**Comment by monotek** [comment]
The docker container is meant to be for testing purposes on your local machine. Therefore nginx inside the container is configured for "localhost" domain. 

You could change the nginx config but without mounts to your docker host all changes and data is lost anyway when the container is stopped.
