### ISSUE TITLE
Elastic Search Error on Running Container

### ISSUE THREAD

**Issue by kagashe** [zammad/zammad-docker#23]
### Infos:

* Docker version: Latest
* Operating system (Docker host): Ubuntu 16

### Expected behavior:

Run Zammad

### Actual behavior:

Error Message

### Steps to reproduce the behavior:

Installed today with docker pull zammad/zammad

all went fine ran the following command

sysctl -w vm.max_map_count=262144

then ran

docker container run -ti --rm --name zammad -p 82:80 zammad/zammad

and now getting this error

[ ok ] Starting PostgreSQL 9.4 database server: main.
[....] Starting Elasticsearch Server:sysctl: setting key "vm.max_map_count": Read-only file system
 failed!

**Comment by monotek** [comment]
Can't reproduce:

```
docker container run -ti --rm --name zammad -p 80:80 zammad/zammad
[ ok ] Starting PostgreSQL 9.4 database server: main.
[....] Starting Elasticsearch Server:sysctl: setting key "vm.max_map_count": Read-only file system
. ok 
[ ok ] Starting Postfix Mail Transport Agent: postfix.
waiting for postgres to be ready...
waiting for postgres to be ready...
waiting for postgres to be ready...
waiting for postgres to be ready...
starting zammad....
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...
waiting for zammad to be ready...

Zammad is ready! Visit http://localhost in your browser!
If you like to use Zammad from somewhere else edit servername directive in /etc/nginx/sites-enabled/zammad.conf!

```

**Comment by monotek** [comment]
How many RAM do you have?

**Comment by kagashe** [comment]
2 GB

**Comment by monotek** [comment]
That's not enough. You need at least 4 GB.
