### ISSUE TITLE
Cannot Build Image

### ISSUE THREAD

**Issue by Robin38219733** [zammad/zammad-docker#24]
### Infos:

* Docker version: 17.09.0-ce, build afdb6d4
* Operating system (Docker host): MacOS 10.13.2 (MacBook Pro Mid 2010 17")

### Expected behavior:

I wanted to build this image local so that i can edit it to run with supervisord and deploy it to my server.
I don't want multiple Containers running so I cant use the Docker Compose Repo...

### Actual behavior:

* Getting the following error:

+ bundle exec rake db:seed
+ bundle exec rake assets:precompile
I, [2017-12-09T15:26:29.299906 #21235]  INFO -- : Writing /opt/zammad/public/assets/application-print-db172409c8422225ac73dfd79ca9fe0994704e3813ebdd759e19cc0e3b0eff6a.css
I, [2017-12-09T15:26:29.302409 #21235]  INFO -- : Writing /opt/zammad/public/assets/application-print-db172409c8422225ac73dfd79ca9fe0994704e3813ebdd759e19cc0e3b0eff6a.css.gz
I, [2017-12-09T15:26:29.307473 #21235]  INFO -- : Writing /opt/zammad/public/assets/print-57d400c28213ca8fb1fc899cd1f3cd91ec5073d4947e60b0b37f2dc2c9937140.css
I, [2017-12-09T15:26:29.307810 #21235]  INFO -- : Writing /opt/zammad/public/assets/print-57d400c28213ca8fb1fc899cd1f3cd91ec5073d4947e60b0b37f2dc2c9937140.css.gz
I, [2017-12-09T15:26:29.635074 #21235]  INFO -- : Writing /opt/zammad/public/assets/app/models/application-76d4e043c2f306db5988fc1a0353623ed827d2246415392d13e405059133a65f.js
I, [2017-12-09T15:26:29.635796 #21235]  INFO -- : Writing /opt/zammad/public/assets/app/models/application-76d4e043c2f306db5988fc1a0353623ed827d2246415392d13e405059133a65f.js.gz
I, [2017-12-09T15:28:02.341499 #21235]  INFO -- : Writing /opt/zammad/public/assets/application-de0f09cf95c6d92ab9d48ee4e80ad6ee117ed27571dd50692d62fe19be6bed31.js
I, [2017-12-09T15:28:02.342203 #21235]  INFO -- : Writing /opt/zammad/public/assets/application-de0f09cf95c6d92ab9d48ee4e80ad6ee117ed27571dd50692d62fe19be6bed31.js.gz
I, [2017-12-09T15:28:09.051172 #21235]  INFO -- : Writing /opt/zammad/public/assets/application-0df52ec3a5b2bb425a35e6fa220efa9bf11061f8075ed1b87021b5f5b6882af2.css
I, [2017-12-09T15:28:09.051938 #21235]  INFO -- : Writing /opt/zammad/public/assets/application-0df52ec3a5b2bb425a35e6fa220efa9bf11061f8075ed1b87021b5f5b6882af2.css.gz
I, [2017-12-09T15:28:09.080570 #21235]  INFO -- : Writing /opt/zammad/public/assets/custom/README-bc77bf2f1b2e58cf0ff57d90b554c900bb6063b60693ed49cc27d6db5b255b81.txt
I, [2017-12-09T15:28:09.080924 #21235]  INFO -- : Writing /opt/zammad/public/assets/custom/README-bc77bf2f1b2e58cf0ff57d90b554c900bb6063b60693ed49cc27d6db5b255b81.txt.gz
I, [2017-12-09T15:28:09.285508 #21235]  INFO -- : Writing /opt/zammad/public/assets/doorkeeper/admin/application-72eac96494badb37c5f96b24ee5582b09288a18197b12635e6329baeac97a231.css
I, [2017-12-09T15:28:09.285956 #21235]  INFO -- : Writing /opt/zammad/public/assets/doorkeeper/admin/application-72eac96494badb37c5f96b24ee5582b09288a18197b12635e6329baeac97a231.css.gz
I, [2017-12-09T15:28:09.312621 #21235]  INFO -- : Writing /opt/zammad/public/assets/doorkeeper/application-b54e8f1303d01fd0d196e12ed469c73ee8f8775fbdc6a28e9172107f4c8e4e33.css
I, [2017-12-09T15:28:09.314519 #21235]  INFO -- : Writing /opt/zammad/public/assets/doorkeeper/application-b54e8f1303d01fd0d196e12ed469c73ee8f8775fbdc6a28e9172107f4c8e4e33.css.gz
+ rm -r tmp/cache
+ bundle exec rails r 'Setting.set('\''es_url'\'', '\''http://localhost:9200'\'')'
+ bundle exec rake searchindex:rebuild
rake aborted!
Unable to process GET at http://localhost:9200
#<UserAgent::Result:0x00000000083202a0 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::EADDRNOTAVAIL: Failed to open TCP connection to localhost:9200 (Cannot assign requested address - connect(2) for \"localhost\" port 9200)>">
/opt/zammad/lib/search_index_backend.rb:29:in `info'
/opt/zammad/lib/tasks/search_index_es.rake:19:in `block (2 levels) in <top (required)>'
/opt/zammad/lib/tasks/search_index_es.rake:121:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => searchindex:rebuild
(See full trace by running task with --trace)

### Steps to reproduce the behavior:

Clone GitHub Repo and try to build Image:
`git clone git@github.com:zammad/zammad-docker.git`
`cd zammad-docker`
`docker build  --tag zammad:latest .`

**Comment by monotek** [comment]
Don't use this image for production. Its the develop version, runs multiple services in one container & you will loose all data on restart.

The error seems to be a not running elasticsearch server. 

Nevertheless such requests are out if scope of our issue tracker. Ask on the community board for help.
