### ISSUE TITLE
Connect External DB Zammad Docker

### ISSUE THREAD

**Issue by augustoferronato** [zammad/zammad-docker#26]
### Infos:

* Docker version:  17.03.2-ce
* Operating system (Docker host): Ubuntu 16.04.4 LTS (with KVM) (4.4.0)

### Expected behavior:

* Possible use the ENV for set a external database for zammad/zammad image

### Actual behavior:

* I try to use the same ENV in the file https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh but is not working

### Steps to reproduce the behavior:

* Create the container, using the ENV variables:

> POSTGRESQL_HOST
> POSTGRESQL_PORT
> POSTGRESQL_USER
> POSTGRESQL_PASS
> POSTGRESQL_DB
> POSTGRESQL_DB_CREATE

But the zammad/zammad ignore and use the internal database, have some differente way for use a external PostgreSQL Database server using the zammad/zammad image?

Thanks

**Comment by monotek** [comment]
Where do you take these vars from?
The single container docker image does not support an external database.
