### ISSUE TITLE
elasticsearch is not started

### ISSUE THREAD

**Issue by andywenk** [zammad/zammad-docker#27]
### Infos:

* Docker version: Docker Desktop Version 2.0.0.0-mac81 (29211)
* Operating system (Docker host): Mac OS Mojave Version 10.14.2 (18C54)

### Expected behavior:

* When I start the docker image with `docker container run -ti --rm --name zammad -p 80:80 zammad/zammad` and I see that elasticsearch is starting, I expect it to be started.

```
~ ❯❯❯ docker container run -ti --rm --name zammad -p 80:80 zammad/zammad

 Starting services...

[ ok ] Starting PostgreSQL 9.6 database server: main.
[ ok ] Starting Elasticsearch Server:.
[ ok ] Starting Postfix Mail Transport Agent: postfix.
Starting memcached: memcached.
[ ok ] Starting nginx: nginx.
```

### Actual behavior:

* elasticsearch is not started

Being in the shell of the image I check the status of elasticsearch and it is not running:

```
root@f3229e48d131:/opt/zammad# /etc/init.d/elasticsearch status
[FAIL] elasticsearch is not running ... failed!
```

I see in the Rails log, that zammad is not able to connect to elasticsearch: 

```
#<UserAgent::Result:0x00007f852d712b68 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::EADDRNOTAVAIL: Failed to open TCP connection to localhost:9200 (Cannot assign requested address - connect(2) for \"localhost\" port 9200)>">
````

### Steps to reproduce the behavior:

* with the given setup, I can reproduce this each time I start the image. Also when I completely remove the image and let docker pull it again (` docker pull zammad/zammad`)

**Comment by monotek** [comment]
Did you run this command before the contianer was started?

`sysctl -w vm.max_map_count=262144`

**Comment by andywenk** [comment]
oh yes I forgot to mention. Yesw I did but it resultzs in an error and I was not sure, if I have to run this command on my mac or in the container.

```
~ ❯❯❯ sysctl -w vm.max_map_count=262144                                                                                                                     
sysctl: unknown oid 'vm.max_map_count'
```

I am confused why I have to do that. And why does it fail? Your help is highly nappreciated. Thanks a lot!

**Comment by monotek** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html

Sorry, no mac user... can't help...

**Comment by andywenk** [comment]
@monotek don't worry - your help is much appreciated. I'll see if I can fix it on my box and reply here again.

**Comment by monotek** [comment]
cool 👍
I reopen until I have time to add it to the docs....

**Comment by andywenk** [comment]
;-)

**Comment by monotek** [comment]
done: https://github.com/zammad/zammad-documentation/commit/b05e751424a9d1070cc650bfc0e2a9c81bce85c5#diff-4dc109f326b2805f3d39275c9b9bedc7

**Comment by andywenk** [comment]
👍
