### ISSUE TITLE
Please provide option for persistent storage of data

### ISSUE THREAD

**Issue by dnauck** [zammad/zammad-docker#3]
The docker image is a nice solution to get Zammad up and running in a few minutes without installing all dependencies and ruby gems.

It would be nice to have an option to persist the Zammad data between restarts and upgrades of the docker image to newer versions.

**Comment by Julian0o** [comment]
+++

**Comment by martini** [comment]
@thorsteneckel I know, this docker image is only for testing. If you would use docker in production, docker-compose would be better. 

But if you test, persistent data would also be fine. How about volumes (info/examples in documentation would be fine)?
https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-

**Comment by monotek** [comment]
I have a docker-compose version with persistent storage ready @ 

https://github.com/monotek/zammad-docker-compose 

please test :-)

**Comment by hhoechtl** [comment]
I modified the compose environment of @monotek to be upgradable via docker image so that your database won't be dropped if you need to rebuild the container, as it's intended by docker that your software version belongs to an image version.

https://github.com/1drop/zammad-docker-compose

**Comment by monotek** [comment]
Thanks for the suggestions :-)
Adopted most of it to my repo. Docker images are now available @ DockerHub -> https://hub.docker.com/r/monotek/zammad-docker-compose/

From now on you only need to:
* sysctl -w vm.max_map_count=262144
* docker-compose up

To update Zammad run:
* docker-compose pull
* docker-compose up

**Comment by monotek** [comment]
We moved my repo to Zammad now. 
https://hub.docker.com/r/zammad/zammad-docker-compose/
With this repo persistent storage works.
Feel free to send more suggestions there :-)
