### ISSUE TITLE
SMTP OpenSSL Error with latest Version

### ISSUE THREAD

**Issue by svenschumacher** [zammad/zammad-docker#32]
### Infos:

* Docker version: 18.09.7
* Operating system (Docker host): Ubuntu 19.04.

### Expected behavior:

* I can update via _docker-compose pull_ and everything works fine. 

### Actual behavior:

* I´ve updated via _docker-compose pull_, everything works fine, except the SMTP connection for sending E-Mails. 

### Steps to reproduce the behavior:

* Update to latest with docker-compose pull
* Send an E-Mail from a ticket
* Receive the error message "Zustellung fehlgeschlagen: "Unable to send email to 'XXXX@XXXX.de': Can't use Channel::Driver::Smtp: #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: unsupported protocol>"

### Workaround
After lots of hours of exchange troubleshooting with the latest tag (3.1.0-7), I decided to switch back to image tag 3.1.0-6, but it didn´t work. First the step back to 3.0.0-15 did the trick. Now everything works fine. 

### Hints
While testing lots of configurations from exchange side, i got different error messages. For example: 

* "net::ReadTimeout" 
* "SSL_connect returned=1 errno=0 state=error: wrong". 

It feels like a problem between Ruby and Elasticsearch.

**Comment by monotek** [comment]
wrong repo. file your bug here: https://github.com/zammad/zammad-docker-compose

**Comment by svenschumacher** [comment]
[Done](https://github.com/zammad/zammad-docker-compose/issues/112). Thanks!
