### ISSUE TITLE
Zammad 3.2.1 release update on Dockerhub

### ISSUE THREAD

**Issue by NickMos** [zammad/zammad-docker#33]
The question is about [Zammad 3.2.1 release ](https://zammad.com/news/release-3-3). Will it be uploaded to the [Dockerhub](https://hub.docker.com/r/zammad/zammad)?

**Comment by monotek** [comment]
Seems versioning of the docker images is broken at the moment. 
I'll have a look later.

But the latest image should work with current version anyway.

**Comment by NickMos** [comment]
Yes, please, take a look.
`later` is not best practice because it could be updated anytime and it could be dangerous for production because of uncontrolled changes inside a new docker image.

**Comment by monotek** [comment]
Please have a look at the readme. 
This is an image for testing only. 
It has no volume.
If you try to update you'll lose all your data.

See: https://github.com/zammad/zammad-docker#what-is-zammad-docker-repo-for

**Comment by NickMos** [comment]
You are right, I've mixed up repositories. You can close the issue here, I will ask at the docker-compose repository about 3.2.1 release. Thank you.
