### ISSUE TITLE
persistence

### ISSUE THREAD

**Issue by Azertooth** [zammad/zammad-docker#44]
can i mount the container on a volume and make it persistent? i tried the docker-compose version but it's outdated and lacking proper documentation

**Comment by MrGeneration** [comment]
Zammad-Docker **is not**m suitable for production use and thus not persistent. 
Please use ``docker-compose`` instead.

**Comment by monotek** [comment]
@Azertooth 
This is a testing image. Don't use it for production.
See: https://github.com/zammad/zammad-docker#what-is-zammad-docker-repo-for

Closing...
