### ISSUE TITLE
Expose Websocket Port Missing

### ISSUE THREAD

**Issue by danielehrhardt** [zammad/zammad-docker#48]
In the dockerfile there is only one expose port. Is the Websocket Port Missing?

**Comment by mgruner** [comment]
This seems to work correctly. Zammad uses the same port as the exposed web server port for the web socket connection, on my system this was `3000`: `ws://127.0.0.1:3000/ws`. You can check this with your browsers's web developer tools to see if the web socket connection is opened and used.
