### ISSUE TITLE
Rename repo to zammad-docker

### ISSUE THREAD

**Issue by monotek** [zammad/zammad-docker#5]
Imho it would be more nice to rename the repo to zammad-docker. If your're clonig to a directory with a lot of other git repos another docker.git directory could already exist.

**Comment by martini** [comment]
@thorsteneckel need to check this

**Comment by martini** [comment]
vote for zammad_docker :)

**Comment by monotek** [comment]
Imho a minus would be better.

We already talked about zammad-mysql & zammad-postrgresql packages. As for now it looks like we need new repos for this and the reponames would also be packagenames on packager.io. Packages with underscores in the name are kind of uncommon... 

Therefore I vote for a minus as devider for all repo names.

**Comment by dnauck** [comment]
@monotek why not depend on official postgresql/mysql docker images instead of creating own ones? Or support docker externe database servers.

**Comment by monotek** [comment]
Thats not the topic. Its about having consistent naming of all repos...

**Comment by thorsteneckel** [comment]
After checking the most common names for non "docker"-only-named repositories via https://hub.docker.com/explore/ and Github search I'll change the name to `docker-zammad`, like `docker-nginx` and `docker-node`. Any objections?
