### ISSUE TITLE
can't run this image

### ISSUE THREAD

**Issue by TianYa-Q** [zammad/zammad-docker#53]
### Infos:

* Docker version:20.10.8
* Operating system (Docker host):Mac

### Actual behavior:
![image](https://user-images.githubusercontent.com/57890911/141784744-30413ec7-cbf9-4020-828e-4fba86e5873b.png)

**Comment by MrGeneration** [comment]
Please use the docker-compose image unless you're not planning to have this productive / testing / loosing data.
