### ISSUE TITLE
On-the-fly update of the docker image

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad-docker#8]
> Hi,
> 
> I wanted to know if one can update the docker image for a running zammad instance? Or do I have to save the database and files somehow and then create a new container? Or is it possible to just update the underlying image so the container starts with all settings, users and so on but with an updated image?
> 
> Thanks in advance and best regards
> Simon

Taken from https://github.com/zammad/zammad/issues/320 - by @Pupp3tm4st3r

**Comment by monotek** [comment]
I have a docker-compose version with persistent storage, which is also automaticly updated on restart, ready @

https://github.com/monotek/zammad-docker-compose

please test :-)

**Comment by monotek** [comment]
We moved my repo to Zammad now. 
With this repo persistent storage and updates via docker image should work.

https://hub.docker.com/r/zammad/zammad-docker-compose/
